tax_advisor/config/routes.rb
TaxAdvisor::Application.routes.draw do
  
  resources :mailings

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :users
  resources :sessions
  resources :password_resets

  get "home/index"
  get "home/about_us"
  get "home/our_clients"
  get "home/tax_guide"
  get "home/services"
  get "home/contacts"
  get "home/payment"
  get "home/alert"
  get "home/pricing"
  

  root :to => 'home#index'
  

  

end

tax_advisor/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
    
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to root_url, :notice => "Password reset instructions sent."
    else
      flash.now.alert = "Could not find a user with that email address."
      render "new"
      #redirect_to new_password_reset_path, flash.now.alert = "Could not find a user with that email address."
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

end

tax_advisor/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

tax_advisor/app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]),:html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>


    <% if @user.errors.any? %>
      <div class="error_messages" id="error_explanation">
        <!-- <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2> -->
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field', :placeholder =>"Password" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field', :placeholder =>"Password Confirmation" %>
      </div>
    </div>


    <div class="form-actions">
      <%= f.submit "Update Password", :class => 'btn btn-primary' %>
    </div>

  </fieldset>
<% end %>

tax_advisor/app/views/password_resets/new.html.erb
<div class="page-header">
  <h2>Reset Password</h2>
</div>

<%= form_tag password_resets_path,:html => { :class => 'form-horizontal' }, :method => :post do %>
  <fieldset>
    <div class="control-group">
      <%= label_tag :email %>
      <div class="controls">
        <%= text_field_tag :email, params[:email], :class => 'text_field', :placeholder =>"Email" %>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag "Reset Password", :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>