tax_advisor/config/routes.rb
TaxAdvisor::Application.routes.draw do
  
  resources :mailings

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :users
  resources :sessions
  resources :password_resets

  get "home/index"
  get "home/about_us"
  get "home/our_clients"
  get "home/tax_guide"
  get "home/services"
  get "home/contacts"
  get "home/payment"
  get "home/alert"
  get "home/pricing"
  

  root :to => 'home#index'
  

  

end

tax_advisor/app/models/mailing.rb
class Mailing < ActiveRecord::Base
  attr_accessible :body, :email, :from, :photo, :subject
end

tax_advisor/app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  # GET /mailings
  # GET /mailings.json
  layout :user_layout
  
  def index
    @mailings = Mailing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailings }
    end
  end

  # GET /mailings/1
  # GET /mailings/1.json
  def show
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/new
  # GET /mailings/new.json
  def new
    @mailing = Mailing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/1/edit
  def edit
    @mailing = Mailing.find(params[:id])
  end

  # POST /mailings
  # POST /mailings.json
  def create
    @mailing = Mailing.new(params[:mailing])
    
    #raise @mailing.inspect
    respond_to do |format|
      if UserMailer.compose_mail(@mailing).deliver
      #if @mailing.save
        format.html { redirect_to new_mailing_path, notice: "Mail was successfully sent to #{@mailing.email}." }
        #format.json { render json: @mailing, status: :created, location: @mailing }
      else
        format.html { render action: "new" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailings/1
  # PUT /mailings/1.json
  def update
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      if @mailing.update_attributes(params[:mailing])
        format.html { redirect_to @mailing, notice: 'Mailing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailings/1
  # DELETE /mailings/1.json
  def destroy
    @mailing = Mailing.find(params[:id])
    @mailing.destroy

    respond_to do |format|
      format.html { redirect_to mailings_url }
      format.json { head :no_content }
    end
  end
end

tax_advisor/app/helpers/mailings_helper.rb
module MailingsHelper
end

tax_advisor/app/views/mailings/_form.html.erb
<%= form_for @mailing, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.hidden_field :from, :value=> current_user.email  %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
<!--
  <div class="control-group">
    <%= f.label :from, :class => 'control-label' %>
    <div class="controls">
      <span class="input-large uneditable-input"><%= current_user.email %></span>
    </div>
  </div>
-->
  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :photo, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                mailings_path, :class => 'btn' %>
  </div>
<% end %>

tax_advisor/app/views/mailings/edit.html.erb
<%- model_class = Mailing -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

tax_advisor/app/views/mailings/index.html.erb
<%- model_class = Mailing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:from) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @mailings.each do |mailing| %>
      <tr>
        <td><%= link_to mailing.id, mailing_path(mailing) %></td>
        <td><%= mailing.email %></td>
        <td><%= mailing.from %></td>
        <td><%= mailing.subject %></td>
        <td><%= mailing.body %></td>
        <td><%= mailing.photo %></td>
        <td><%=l mailing.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_mailing_path(mailing), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mailing_path(mailing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mailing_path,
            :class => 'btn btn-primary' %>

tax_advisor/app/views/mailings/new.html.erb
<%- model_class = Mailing -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

tax_advisor/app/views/mailings/show.html.erb
<%- model_class = Mailing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @mailing.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @mailing.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @mailing.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @mailing.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo) %>:</strong></dt>
  <dd><%= @mailing.photo %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              mailings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mailing_path(@mailing), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              mailing_path(@mailing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>